name: Linux CI

on:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  build:
    name: Build & Test (Ubuntu)
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@7b7c407752d8230469b848039911fc72c2b6499f # stable
        with:
          toolchain: stable

      - name: Cache cargo registry
        uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4.0.2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            Linux/target
          key: ${{ runner.os }}-cargo-${{ hashFiles('Linux/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-

      - name: Build workspace
        run: cargo build --workspace
        working-directory: Linux

      - name: Run tests
        run: cargo test --workspace
        working-directory: Linux

  check-cross:
    name: Cargo Check (cross-platform sanity)
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - uses: dtolnay/rust-toolchain@7b7c407752d8230469b848039911fc72c2b6499f # stable
      - run: cargo check --workspace
        working-directory: Linux
