name: Windows CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - uses: dtolnay/rust-toolchain@7b7c407752d8230469b848039911fc72c2b6499f # stable
        with:
          toolchain: stable
          targets: x86_64-pc-windows-msvc

      - uses: Swatinem/rust-cache@23bce251a8cd2ffc3c1075edd2367cf4999c6d8e # v2.7.3
        with:
          workspaces: Windows

      - name: Build workspace
        run: cargo build --workspace
        working-directory: Windows

      - name: Run tests
        run: cargo test --workspace
        working-directory: Windows
